export const FETCH_BLOGS_START = 'FETCH_BLOGS_START'
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS'
export const FETCH_BLOGS_FAILED = 'FETCH_BLOGS_FAILED'

export const FETCH_BLOG_LABEL_START = 'FETCH_BLOG_LABEL_START'
export const FETCH_BLOG_LABEL_SUCCESS = 'FETCH_BLOG_LABEL_SUCCESS'
export const FETCH_BLOG_LABEL_FAILED = 'FETCH_BLOG_LABEL_FAILED'

export const FETCH_BLOG_FROM_LABEL_START = 'FETCH_BLOG_FROM_LABEL_START'
export const FETCH_BLOG_FROM_LABEL_SUCCESS = 'FETCH_BLOG_FROM_LABEL_SUCCESS'
export const FETCH_BLOG_FROM_LABEL_FAILED = 'FETCH_BLOG_FROM_LABEL_FAILED'
