export const FETCH_BLOG_START = 'FETCH_BLOG_START'
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS'
export const FETCH_BLOG_FAILED = 'FETCH_BLOG_FAILED'

export const FETCH_BLOG_LABEL_START = 'FETCH_BLOG_LABEL_START'
export const FETCH_BLOG_LABEL_SUCCESS = 'FETCH_BLOG_LABEL_SUCCESS'
export const FETCH_BLOG_LABEL_FAILED = 'FETCH_BLOG_LABEL_FAILED'

export const FETCH_BLOG_FROM_LABEL_START = 'FETCH_BLOG_FROM_LABEL_START'
export const FETCH_BLOG_FROM_LABEL_SUCCESS = 'FETCH_BLOG_FROM_LABEL_SUCCESS'
export const FETCH_BLOG_FROM_LABEL_FAILED = 'FETCH_BLOG_FROM_LABEL_FAILED'
