export const SHOW_MODAL = 'SHOW_PDF_MODAL'
export const HIDE_MODAL = 'HIDE_PDF_MODAL'
export const FAILED_MODAL = 'FAILED_PDF_MODAL'

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL'
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL'
