export const SHOW_PDF_MODAL = 'SHOW_PDF_MODAL'
export const HIDE_PDF_MODAL = 'HIDE_PDF_MODAL'
export const FAILED_MODAL = 'FAILED_PDF_MODAL'

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL'
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL'

export const SHOW_PROFILE_MODAL = 'SHOW_PROFILE_MODAL'
export const HIDE_PROFILE_MODAL = 'HIDE_PROFILE_MODAL'

export const SHOW_SUBSCRIPTION_MODAL = 'SHOW_SUBSCRIPTION_MODAL'
export const HIDE_SUBSCRIPTION_MODAL = 'HIDE_SUBSCRIPTION_MODAL'
