export const FETCH_USER_PROFILE_START = 'FETCH_USER_PROFILE_START'
export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE'
